name: Versioning Test

on:
  push:
    branches:
      - '*'

jobs:
  version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Stage changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .

      - name: Commit changes
        run: |
          git commit -m "Update version" || true

      - name: Determine version and apply
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            npm version major
          elif [[ "${{ github.ref }}" == "refs/heads/minor" ]]; then
            npm version minor
          elif [[ "${{ github.ref }}" == "refs/heads/pre-minor" ]]; then
            npm version prerelease --preid=rc
          elif [[ "${{ github.ref }}" == "refs/heads/pre-patch" ]]; then
            npm version prerelease --preid=rc
          elif [[ "${{ github.ref }}" == "refs/heads/pre-patch" && "${{ github.base_ref }}" == "refs/heads/minor" ]]; then
            npm version patch
          else
            npm version patch
          fi

          # Publicar el tag y la versión
          git push --follow-tags
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_TOKEN}}

